### ISSUE TITLE
parser

### ISSUE THREAD

**Issue by mattiaerre** [mattiaerre/prettier-plugin-solidity#1]
# Description

as per the [prettier plugins doc](), "Parsers convert code as a string into an AST." and so I'd love to take advantage of one of these libraries if they produce the right AST

- ~~https://github.com/ConsenSys/solidity-parser~~

- https://github.com/federicobond/solidity-parser-antlr

// cc @federicobond @lydell

**Comment by federicobond** [comment]
solidity-parser by ConsenSys is deprecated. Let me know if you need any help with  solidity-parser-antlr!

**Comment by mattiaerre** [comment]
thank you so much @federicobond for your reply, I will try to use `solidity-parser-antlr` and let you know how it goes; actually I've got already a question for you: it looks like the parser throws an error when it encounters the `require()` function; here you can see the error thrown:

```bash
[error] src/contracts/Lottery.sol: Error
[error]     at new ParserError (/Users/mrichetto/projects/prettier-plugin-solidity/node_modules/solidity-parser-antlr/src/index.js:12:16)
[error]     at Object.parse (/Users/mrichetto/projects/prettier-plugin-solidity/node_modules/solidity-parser-antlr/src/index.js:53:11)
[error]     at Object.parse (/Users/mrichetto/projects/prettier-plugin-solidity/src/parser.js:9:17)
[error]     at Object.parse$3 [as parse] (/Users/mrichetto/projects/learn-ethereum-and-solidity/node_modules/prettier/bin-prettier.js:23712:19)
[error]     at formatWithCursor (/Users/mrichetto/projects/learn-ethereum-and-solidity/node_modules/prettier/bin-prettier.js:29396:27)
[error]     at Object.formatWithCursor (/Users/mrichetto/projects/learn-ethereum-and-solidity/node_modules/prettier/bin-prettier.js:29697:12)
[error]     at format$1 (/Users/mrichetto/projects/learn-ethereum-and-solidity/node_modules/prettier/bin-prettier.js:35857:21)
[error]     at eachFilename (/Users/mrichetto/projects/learn-ethereum-and-solidity/node_modules/prettier/bin-prettier.js:36082:16)
[error]     at filePaths.forEach.filePath (/Users/mrichetto/projects/learn-ethereum-and-solidity/node_modules/prettier/bin-prettier.js:36022:7)
[error]     at Array.forEach (<anonymous>)
```

**Comment by federicobond** [comment]
I cannot reproduce it, unfortunately. Can you open an issue on the parser repo with a simplified test case demonstrating the error?

**Comment by mattiaerre** [comment]
sure, I'll do it asap; thanks @federicobond

**Comment by mattiaerre** [comment]
hi @federicobond I've created this issue:

https://github.com/federicobond/solidity-parser-antlr/issues/21

thanks,
-Mattia

**Comment by mattiaerre** [comment]
👋
